language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
    - CIBW_SKIP='cp35-*'
    - TWINE_USERNAME=kavvkon
      # Note: TWINE_PASSWORD is set in Travis settings

script:
  - $PIP install cibuildwheel==0.10.0
  - cibuildwheel ./gdxcc --output-dir wheelhouse
  - cibuildwheel ./gamsxcc --output-dir wheelhouse
  - cibuildwheel ./optcc --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload wheelhouse/*.whl
    fi