matrix:
  include:
    - sudo: required
      language: python
      services:
        - docker
    - os: osx
      language: generic
      before_install:
        - brew update
        - brew install python
        - virtualenv env -p python
        - source env/bin/activate

env:
  global:
    - CIBW_SKIP: cp33-* cp35-*
    - TWINE_USERNAME: kavvkon
      # Note: TWINE_PASSWORD is set in Travis settings

script:
  - pip install cibuildwheel==0.6.0
  - cibuildwheel ./gdxcc --output-dir wheelhouse
  - cibuildwheel ./gamsxcc --output-dir wheelhouse
  - cibuildwheel ./optcc --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload wheelhouse/*.whl
    fi