language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
      - PIP=pip
      - GAMS_URL="https://d37drm4t2jghv5.cloudfront.net/distributions/24.9.2/linux/linux_x64_64_sfx.exe"
    - os: osx
      language: generic
      env:
      - PIP=pip2
      - GAMS_URL="https://d37drm4t2jghv5.cloudfront.net/distributions/24.9.2/macosx/GAMS24.9.dmg"

env:
  global:
    - CIBW_SKIP='cp35-*'
    - CIBW_TEST_REQUIRES='pytest'
    - CIBW_TEST_COMMAND='pytest -v {project}/tests/'
    - TWINE_USERNAME=kavvkon
      # Note: TWINE_PASSWORD is set in Travis settings
    - GAMS=24.9

install:
  # Install GAMS
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget -N $GAMS_URL -O gams.zip;
      unzip -qu gams.zip -d $HOME;
      ln -s $HOME/gams${GAMS}_linux_x64_64_sfx ${TRAVIS_BUILD_DIR}/gams;
      ls ${TRAVIS_BUILD_DIR}/gams;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      wget -N $GAMS_URL -O gams.dmg;
      hdiutil attach gams.dmg;
      ls /Volumes;
      cp -r /Volumes/GAMS*/* ${TRAVIS_BUILD_DIR}/gams;
      hdiutil detach -force /Volumes/GAMS24.9;
    fi

  - export PATH="$HOME/gams:$PATH"
  # - cd $HOME/gams
  # - gamsinst -a
  # - cd -

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        export CIBW_ENVIRONMENT="GAMS_DIR=/host$TRAVIS_BUILD_DIR/gams";
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        export CIBW_ENVIRONMENT="GAMS_DIR=$TRAVIS_BUILD_DIR/gams";
    fi
  - $PIP install cibuildwheel==0.10.0
  - cibuildwheel ./gdxcc --output-dir wheelhouse
  - cibuildwheel ./gamsxcc --output-dir wheelhouse
  - cibuildwheel ./optcc --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      $PIP install twine
      python -m twine upload wheelhouse/*.whl
    fi