language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
    - CIBW_SKIP='cp35-*'
    - CIBW_TEST_REQUIRES='pytest'
    - CIBW_TEST_COMMAND='pytest -v {project}/tests/'
    - CIBW_ENVIRONMENT='GAMS_DIR=/host$(TRAVIS_BUILD_DIR)/gams'
    - TWINE_USERNAME=kavvkon
      # Note: TWINE_PASSWORD is set in Travis settings
    - GAMS=24.9
    - GAMS_URL=https://d37drm4t2jghv5.cloudfront.net/distributions/24.9.2/linux/linux_x64_64_sfx.exe

install:
  # Install GAMS
  - wget -N $GAMS_URL -O gams.zip
  - unzip -qu gams.zip -d $HOME
  - ln -s $HOME/gams$(GAMS)_linux_x64_64_sfx $(TRAVIS_BUILD_DIR)/gams #ln to root
  - export PATH="$HOME/gams:$PATH"
  # - cd $HOME/gams
  # - gamsinst -a
  # - cd -


script:
  - $PIP install cibuildwheel==0.10.0
  - cibuildwheel ./gdxcc --output-dir wheelhouse
  - cibuildwheel ./gamsxcc --output-dir wheelhouse
  - cibuildwheel ./optcc --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      $PIP install twine
      python -m twine upload wheelhouse/*.whl
    fi