environment:
  global:
    CIBW_SKIP: cp35-*
    CIBW_TEST_REQUIRES: 'pytest'
    CIBW_TEST_COMMAND: 'pytest -v {project}/tests/'
    CIBW_ENVIRONMENT: 'GAMS_DIR=%APPVEYOR_BUILD_FOLDER%/gams'
    TWINE_USERNAME: kavvkon
    # Note: TWINE_PASSWORD is set in Appveyor settings

build_script:
  - pip install cibuildwheel==0.10.0
  - cibuildwheel ./gdxcc --output-dir wheelhouse
  - cibuildwheel ./gamsxcc --output-dir wheelhouse
  - cibuildwheel ./optcc --output-dir wheelhouse
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        python -m pip install twine
        python -m twine upload (resolve-path wheelhouse\*.whl)
      }
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels